
OPENROUTER_API_KEY = "YOUR-OPENROUTER-API-KEY"  # API key OpenRouter
CURRENCYFREAKS_API_KEY = "YOUR-CURRENCYFREAKS-API-KEY"  # Api key dari CurrencyFreaks
DISCORD_BOT_TOKEN = "YOUR-BOT-TOKEN"  # token bot discord
