import random

def get_fun_fact():
    local_facts = [
        "Otak manusia lebih aktif saat malam hari.",
        "Lumba-lumba memberi nama satu sama lain.",
        "Tawon bisa mengenali wajah manusia."
        "Ikan hiu kehilangan lebih dari 6.000 gigi setiap tahun, dan gigi barunya tumbuh dalam waktu 24 jam.",
            "Julius Caesar tewas dengan 23 tikaman.",
            "Nama mobil Nissan berasal dari bahasa Jepang: 'ni' berarti 2 dan 'san' berarti 3.",
            "Jerapah dan tikus bisa bertahan hidup lebih lama tanpa air daripada unta.",
            "Kucing takut dengan air.",
            "Kambing bisa pingsan kalau kaget.",
            "Monyet bisa mengobati luka-lukanya sendiri.",
            "Kuda bisa tidur sambil berdiri.",
            "Sebelum Masehi dalam bahasa Inggris adalah B.C. (Before Christ), setelah Masehi adalah A.D. (Anno Domini).",
            "Nama mobil Nissan berasal dari bahasa Jepang: 'ni' berarti 2 dan 'san' berarti 3.",
            "Jerapah dan tikus bisa bertahan hidup lebih lama tanpa air daripada unta.",
            "Kucing takut dengan air.",
            "Kambing bisa pingsan kalau kaget.",
            "Monyet bisa mengobati luka-lukanya sendiri.",
            "Kuda bisa tidur sambil berdiri.",
            "Sebelum Masehi dalam bahasa Inggris adalah B.C. (Before Christ), setelah Masehi adalah A.D. (Anno Domini).",
            "Nama mobil Nissan berasal dari bahasa Jepang: 'ni' berarti 2 dan 'san' berarti 3.",
            "Jerapah dan tikus bisa bertahan hidup lebih lama tanpa air daripada unta.",
            "Kucing takut dengan air.",
            "Kambing bisa pingsan kalau kaget.",
            "Monyet bisa mengobati luka-lukanya sendiri.",
            "Kuda bisa tidur sambil berdiri.",
            "Sebelum Masehi dalam bahasa Inggris adalah B.C. (Before Christ), setelah Masehi adalah A.D. (Anno Domini).",
            "Nama mobil Nissan berasal dari bahasa Jepang: 'ni' berarti 2 dan 'san' berarti 3.",
            "Jerapah dan tikus bisa bertahan hidup lebih lama tanpa air daripada unta.",
            "Kucing takut dengan air.",
            "Kambing bisa pingsan kalau kaget.",
            "Monyet bisa mengobati luka-lukanya sendiri.",
            "Kuda bisa tidur sambil berdiri.",
            "Sebelum Masehi dalam bahasa Inggris adalah B.C. (Before Christ), setelah Masehi adalah A.D. (Anno Domini).",
            "Nama mobil Nissan berasal dari bahasa Jepang: 'ni' berarti 2 dan 'san' berarti 3.",
            "Jerapah dan tikus bisa bertahan hidup lebih lama tanpa air daripada unta.",
            "Kucing takut dengan air.",
            "Kambing bisa pingsan kalau kaget.",
            "Monyet bisa mengobati luka-lukanya sendiri.",
            "Kuda bisa tidur sambil berdiri.",
            "Sebelum Masehi dalam bahasa Inggris adalah B.C. (Before Christ), setelah Masehi adalah A.D. (Anno Domini).",
            "Nama mobil Nissan berasal dari bahasa Jepang: 'ni' berarti 2 dan 'san' berarti 3.",
            "Jerapah dan tikus bisa bertahan hidup lebih lama tanpa air daripada unta.",
            "Kucing takut dengan air.",
            "Kambing bisa pingsan kalau kaget.",
            "Monyet bisa mengobati luka-lukanya sendiri.",
            "Kuda bisa tidur sambil berdiri.",
            "Sebelum Masehi dalam bahasa Inggris adalah B.C. (Before Christ), setelah Masehi adalah A.D. (Anno Domini).",
            "Nama mobil Nissan berasal dari bahasa Jepang: 'ni' berarti 2 dan 'san' berarti 3.",
            "Jerapah dan tikus bisa bertahan hidup lebih lama tanpa air daripada unta.",
            "Kucing takut dengan air.",
            "Kambing bisa pingsan kalau kaget.",
            "Monyet bisa mengobati luka-lukanya sendiri.",
            "Kuda bisa tidur sambil berdiri.",
            "Sebelum Masehi dalam bahasa Inggris adalah B.C. (Before Christ), setelah Masehi adalah A.D. (Anno Domini).",
            "Nama mobil Nissan berasal dari bahasa Jepang: 'ni' berarti 2 dan 'san' berarti 3.",
            "Jerapah dan tikus bisa bertahan hidup lebih lama tanpa air daripada unta.",
            "Kucing takut dengan air.",
            "Kambing bisa pingsan kalau kaget.",
            "Monyet bisa mengobati luka-lukanya sendiri.",
            "Kuda bisa tidur sambil berdiri.",
            "Sebelum Masehi dalam bahasa Inggris adalah B.C. (Before Christ), setelah Masehi adalah A.D. (Anno Domini).",
            "Nama mobil Nissan berasal dari bahasa Jepang: 'ni' berarti 2 dan 'san' berarti 3.",
            "Jerapah dan tikus bisa bertahan hidup lebih lama tanpa air daripada unta.",
            "Kucing takut dengan air.",
            "Kambing bisa pingsan kalau kaget.",
            "Monyet bisa mengobati luka-lukanya sendiri.",
            "Kuda bisa tidur sambil berdiri.",
            "Sebelum Masehi dalam bahasa Inggris adalah B.C. (Before Christ), setelah Masehi adalah A.D. (Anno Domini).",
            "Nama mobil Nissan berasal dari bahasa Jepang: 'ni' berarti 2 dan 'san' berarti 3.",
            "Jerapah dan tikus bisa bertahan hidup lebih lama tanpa air daripada unta.",
            "Kucing takut dengan air.",
            "Kambing bisa pingsan kalau kaget.",
            "Monyet bisa mengobati luka-lukanya sendiri.",
            "Kuda bisa tidur sambil berdiri.",
            "Sebelum Masehi dalam bahasa Inggris adalah B.C. (Before Christ), setelah Masehi adalah A.D. (Anno Domini).",
            "Nama mobil Nissan berasal dari bahasa Jepang: 'ni' berarti 2 dan 'san' berarti 3.",
            "Jerapah dan tikus bisa bertahan hidup lebih lama tanpa air daripada unta.",
            "Kucing takut dengan air.",
            "Kambing bisa pingsan kalau kaget.",
            "Monyet bisa mengobati luka-lukanya sendiri.",
            "Kuda bisa tidur sambil berdiri.",
    ]
    return random.choice(local_facts)
