import random

questions = [
    {"pertanyaan": "Apa ibu kota Indonesia?", "jawaban": "jakarta"},
    {"pertanyaan": "Berapakah hasil dari 7 x 8?", "jawaban": "56"},
    {"pertanyaan": "Apa ibu kota Indonesia?", "jawaban": "jakarta"},
    {"pertanyaan": "2 + 2 = ?", "jawaban": "4"},
    {"pertanyaan": "Warna bendera Jepang?", "jawaban": "putih dan merah"},
    {"pertanyaan": "Apa ibu kota Indonesia?", "jawaban": "jakarta"},
    {"pertanyaan": "2 + 2 = ?", "jawaban": "4"},
    {"pertanyaan": "Warna bendera Jepang?", "jawaban": "putih dan merah"},
    {"pertanyaan": "Apa ibu kota Indonesia?", "jawaban": "Jakarta"},
    {"pertanyaan": "Planet ke-3 dari Matahari adalah?", "jawaban": "Bumi"},
    {"pertanyaan": "Siapa presiden pertama Indonesia?", "jawaban": "Soekarno"},
    {"pertanyaan": "Gunung tertinggi di dunia?", "jawaban": "Everest"},
    {"pertanyaan": "Ibukota Jepang?", "jawaban": "Tokyo"},
    {"pertanyaan": "Lambang kimia untuk air?", "jawaban": "H2O"},
    {"pertanyaan": "Berapa hasil dari 5 x 6?", "jawaban": "30"},
    {"pertanyaan": "Siapa yang menulis 'Harry Potter'?", "jawaban": "J.K. Rowling"},
    {"pertanyaan": "Hewan tercepat di darat?", "jawaban": "Cheetah"},
    {"pertanyaan": "Bahasa resmi Brasil?", "jawaban": "Portugis"},
    {"pertanyaan": "Siapa penemu bola lampu?", "jawaban": "Thomas Edison"},
    {"pertanyaan": "Binatang apa yang dikenal bisa berubah warna?", "jawaban": "Bunglon"},
    {"pertanyaan": "Lambang kimia emas?", "jawaban": "Au"},
    {"pertanyaan": "Siapa presiden AS ke-44?", "jawaban": "Barack Obama"},
    {"pertanyaan": "Alat musik tradisional Bali?", "jawaban": "Gamelan"},
    {"pertanyaan": "Ibukota Australia?", "jawaban": "Canberra"},
    {"pertanyaan": "Gunung tertinggi di Indonesia?", "jawaban": "Puncak Jaya"},
    {"pertanyaan": "Planet terbesar di tata surya?", "jawaban": "Jupiter"},
    {"pertanyaan": "Nama samudra terbesar?", "jawaban": "Pasifik"},
    {"pertanyaan": "Organ tubuh untuk memompa darah?", "jawaban": "Jantung"},
    {"pertanyaan": "Hewan mamalia terbesar?", "jawaban": "Paus biru"},
    {"pertanyaan": "Alat optik untuk melihat bintang?", "jawaban": "Teleskop"},
    {"pertanyaan": "Siapa penemu pesawat terbang?", "jawaban": "Wright bersaudara"},
    {"pertanyaan": "Negara dengan piramida tertua?", "jawaban": "Mesir"},
    {"pertanyaan": "Ibu kota Inggris?", "jawaban": "London"},
    {"pertanyaan": "Simbol kimia untuk besi?", "jawaban": "Fe"},
    {"pertanyaan": "Berapa jumlah warna pelangi?", "jawaban": "7"},
    {"pertanyaan": "Siapa tokoh detektif ciptaan Sir Arthur Conan Doyle?", "jawaban": "Sherlock Holmes"},
    {"pertanyaan": "Suku asli Australia?", "jawaban": "Aborigin"},
    {"pertanyaan": "Negara penghasil kopi terbesar?", "jawaban": "Brasil"},
    {"pertanyaan": "Nama gunung berapi terkenal di Italia?", "jawaban": "Vesuvius"},
    {"pertanyaan": "Film animasi berisi karakter Woody dan Buzz?", "jawaban": "Toy Story"},
    {"pertanyaan": "Nama ilmiah manusia?", "jawaban": "Homo sapiens"},
    {"pertanyaan": "Organ tubuh tempat terjadinya pencernaan pertama?", "jawaban": "Mulut"},
    {"pertanyaan": "Berapa sisi segitiga?", "jawaban": "3"},
    {"pertanyaan": "Benua terbesar?", "jawaban": "Asia"},
    {"pertanyaan": "Negara dengan populasi terbanyak?", "jawaban": "Tiongkok"},
    {"pertanyaan": "Siapa yang menyusun teori relativitas?", "jawaban": "Albert Einstein"},
    {"pertanyaan": "Pulau terbesar di dunia?", "jawaban": "Greenland"},
    {"pertanyaan": "Pahlawan wanita Indonesia terkenal dari Aceh?", "jawaban": "Cut Nyak Dien"},
    {"pertanyaan": "Bahan bakar utama mobil?", "jawaban": "Bensin"},
    {"pertanyaan": "Negara dengan bendera merah-putih seperti Indonesia?", "jawaban": "Polandia"},
    {"pertanyaan": "Huruf pertama dalam alfabet Yunani?", "jawaban": "Alpha"},
    {"pertanyaan": "Hewan dengan leher panjang?", "jawaban": "Jerapah"},
    {"pertanyaan": "Apa nama hewan tercepat di udara?", "jawaban": "Elang peregrine"},
    {"pertanyaan": "Nama alat untuk mengukur suhu?", "jawaban": "Termometer"},
    {"pertanyaan": "Siapa yang menyusun hukum gravitasi?", "jawaban": "Isaac Newton"},
    {"pertanyaan": "Hewan berkantung dari Australia?", "jawaban": "Kanguru"},
    {"pertanyaan": "Ibukota Prancis?", "jawaban": "Paris"},
    {"pertanyaan": "Planet yang memiliki cincin besar?", "jawaban": "Saturnus"},
    {"pertanyaan": "Bahasa utama di Kanada?", "jawaban": "Inggris dan Prancis"},
    {"pertanyaan": "Siapa penyanyi lagu 'Shape of You'?", "jawaban": "Ed Sheeran"},
    {"pertanyaan": "Bulan keempat dalam kalender?", "jawaban": "April"},
    {"pertanyaan": "Benua tempat Indonesia berada?", "jawaban": "Asia"},
    {"pertanyaan": "Organ utama sistem pernapasan?", "jawaban": "Paru-paru"},
    {"pertanyaan": "Logam ringan untuk membuat pesawat?", "jawaban": "Aluminium"},
    {"pertanyaan": "Negara yang terkenal dengan kimono?", "jawaban": "Jepang"},
    {"pertanyaan": "Siapa penemu telepon?", "jawaban": "Alexander Graham Bell"},
    {"pertanyaan": "Ibukota Malaysia?", "jawaban": "Kuala Lumpur"},
    {"pertanyaan": "Pulau tempat candi Borobudur?", "jawaban": "Jawa"},
    {"pertanyaan": "Simbol kimia untuk oksigen?", "jawaban": "O"},
    {"pertanyaan": "Jumlah pemain sepak bola di lapangan?", "jawaban": "11"},
    {"pertanyaan": "Hewan lambang negara Indonesia?", "jawaban": "Garuda"},
    {"pertanyaan": "Hari Kemerdekaan Indonesia?", "jawaban": "17 Agustus"},
    {"pertanyaan": "Nama alat untuk mengetik?", "jawaban": "Keyboard"},
    {"pertanyaan": "Mata uang Jepang?", "jawaban": "Yen"},
    {"pertanyaan": "Bagian tumbuhan untuk fotosintesis?", "jawaban": "Daun"},
    {"pertanyaan": "Planet terkecil di tata surya?", "jawaban": "Merkurius"},
    {"pertanyaan": "Negara dengan Menara Eiffel?", "jawaban": "Prancis"},
    {"pertanyaan": "Siapa yang dikenal dengan julukan 'Bapak Proklamator'?", "jawaban": "Soekarno"},
    {"pertanyaan": "Apa warna darah dalam tubuh?", "jawaban": "Merah"},
    {"pertanyaan": "Apa nama lautan antara Indonesia dan Australia?", "jawaban": "Laut Timor"},
    {"pertanyaan": "Siapa pelukis 'Mona Lisa'?", "jawaban": "Leonardo da Vinci"},
    {"pertanyaan": "Benda langit yang mengelilingi planet?", "jawaban": "Satelit"},
    {"pertanyaan": "Hewan yang hidup di kutub?", "jawaban": "Beruang kutub"},
    {"pertanyaan": "Negara asal pizza?", "jawaban": "Italia"},
    {"pertanyaan": "Apa nama organ tubuh untuk mendengar?", "jawaban": "Telinga"},
    {"pertanyaan": "Warna campuran merah dan biru?", "jawaban": "Ungu"},
    {"pertanyaan": "Kapan Hari Pahlawan Indonesia?", "jawaban": "10 November"},
    {"pertanyaan": "Apa nama benua di kutub selatan?", "jawaban": "Antartika"},
    {"pertanyaan": "Hewan yang disebut 'Raja Hutan'?", "jawaban": "Singa"},
    {"pertanyaan": "Negara dengan Tembok Besar?", "jawaban": "Tiongkok"},
    {"pertanyaan": "Satuan untuk mengukur arus listrik?", "jawaban": "Ampere"},
    {"pertanyaan": "Siapa yang menemukan teori evolusi?", "jawaban": "Charles Darwin"},
    {"pertanyaan": "Apa nama benua terkecil?", "jawaban": "Australia"},
    {"pertanyaan": "Planet terdekat dari Matahari?", "jawaban": "Merkurius"},
    {"pertanyaan": "Apa nama bagian bunga yang menghasilkan biji?", "jawaban": "Putik"},
    {"pertanyaan": "Organisme mikroskopis penyebab penyakit?", "jawaban": "Bakteri"},
    {"pertanyaan": "Siapa yang pertama kali ke bulan?", "jawaban": "Neil Armstrong"},
    {"pertanyaan": "Negara dengan populasi Muslim terbesar?", "jawaban": "Indonesia"},
    {"pertanyaan": "Mata uang Amerika Serikat?", "jawaban": "Dolar"},
    {"pertanyaan": "Siapa superhero dengan palu bernama Mjölnir?", "jawaban": "Thor"},
    {"pertanyaan": "Film Avengers diproduksi oleh?", "jawaban": "Marvel"},
    {"pertanyaan": "Benda langit yang memberi cahaya malam?", "jawaban": "Bulan"},
    {"pertanyaan": "Nama sistem bilangan biner terdiri dari?", "jawaban": "0 dan 1"},
]

current_quiz = {}

def get_quiz_question(user_id):
    soal = random.choice(questions)
    current_quiz[user_id] = soal
    return soal

def check_answer(user_id, user_answer):
    if user_id not in current_quiz:
        return None
    jawaban_benar = current_quiz[user_id]['jawaban'].lower()
    del current_quiz[user_id]
    return user_answer.lower().strip() == jawaban_benar, jawaban_benar
