import requests
import random

def get_random_quote():
    try:
        response = requests.get("https://api.quotable.io/random", timeout=5)
        data = response.json()
        return f"\"{data['content']}\" — {data['author']}"
    except:
        local_quotes = [
            "Success is a journey, not a destination."
            "Kegagalan adalah bumbu yang memberi rasa pada kesuksesan.",
            "Semangat adalah bahan bakar utama menuju mimpi.",
            "Kesuksesan berawal dari keyakinan pada diri sendiri.",
            "Jangan menyerah, awal yang sulit sering menghasilkan akhir yang indah.",
            "Setiap hari adalah kesempatan baru untuk menjadi lebih baik.",
            "Keberhasilan dimulai dari mimpi yang besar dan tindakan yang nyata.",
            "Hidup bukan tentang menunggu badai reda, tapi belajar menari di tengah hujan.",
            "Usaha tidak akan mengkhianati hasil.",
            "Kegagalan adalah bagian dari proses menuju keberhasilan.",
            "Satu langkah kecil hari ini lebih baik daripada tidak melangkah sama sekali.",
            "Kesuksesan datang kepada mereka yang tidak pernah berhenti mencoba.",
            "Yakin bisa, pasti bisa!",
            "Hidupmu berharga, jangan pernah menyerah.",
            "Perubahan kecil bisa membawa dampak besar.",
            "Jadilah versi terbaik dari dirimu setiap hari.",
            "Hargai proses, nikmati hasilnya.",
            "Kamu lebih kuat dari yang kamu pikirkan.",
            "Lakukan yang terbaik, selebihnya serahkan pada Tuhan.",
            "Bermimpilah setinggi langit, tapi tetap injakkan kaki di bumi.",
            "Jangan takut gagal, takutlah untuk tidak mencoba.",
            "Berbuat baik tak pernah sia-sia.",
            "Ketekunan hari ini adalah keberhasilan esok hari.",
            "Percaya pada dirimu sendiri adalah awal dari segalanya.",
            "Banyak hal besar dimulai dari langkah kecil.",
            "Lebih baik lelah berjuang daripada menyesal karena menyerah.",
            "Keberanian bukan tidak takut, tapi tetap melangkah meski takut.",
            "Waktu adalah guru terbaik, walau terkadang muridnya keras kepala.",
            "Belajarlah dari kemarin, hiduplah untuk hari ini, dan berharaplah untuk besok.",
            "Ciptakan kesempatan, jangan menunggunya.",
            "Jangan menunggu motivasi, mulailah dari disiplin.",
            "Langkah pertama adalah yang paling penting.",
            "Bersyukur menjadikan hidup lebih indah.",
            "Tantangan adalah peluang untuk tumbuh.",
            "Keraguan membunuh lebih banyak mimpi daripada kegagalan.",
            "Kesuksesan bukan tujuan, tapi perjalanan.",
            "Setiap detik adalah peluang untuk berubah.",
            "Hidup adalah pilihan, buatlah yang terbaik.",
            "Sukses adalah hasil dari kerja keras dan doa.",
            "Yang lambat tapi konsisten akan sampai tujuan.",
            "Hidup itu singkat, lakukan hal bermakna.",
            "Jadilah cahaya di tengah kegelapan.",
            "Kesalahan adalah guru terbaik.",
            "Kerjakan dengan hati, hasilkan yang berarti.",
            "Percaya diri adalah kunci pertama sukses.",
            "Terus belajar dan tumbuh setiap hari.",
            "Jangan bandingkan dirimu dengan orang lain.",
            "Fokus pada tujuan, bukan hambatan.",
            "Kebaikan itu menular.",
            "Jangan pernah meremehkan dirimu sendiri.",
            "Ambil tindakan sekarang juga.",
            "Sukses datang dari keberanian untuk memulai.",
            "Setiap orang punya waktunya masing-masing.",
            "Tetap rendah hati dalam keberhasilan.",
            "Don't give up. Great things take time.",
            "Every day is a second chance.",
            "Believe in yourself and all that you are.",
            "Success is no accident. It is hard work and perseverance.",
            "Your only limit is your mind.",
            "Dream big, work hard, stay focused.",
            "Happiness is a journey, not a destination.",
            "Failure is simply the opportunity to begin again.",
            "Success doesn't come from what you do occasionally, it comes from what you do consistently.",
            "You are stronger than you think.",
            "Start where you are. Use what you have. Do what you can.",
            "Push yourself, because no one else is going to do it for you.",
            "Success is not for the lazy.",
            "Be the change that you wish to see in the world.",
            "Stay positive, work hard, make it happen.",
            "The best time for new beginnings is now.",
            "Little things make big days.",
            "Your vibe attracts your tribe.",
            "Believe you can and you're halfway there.",
            "You don’t have to be perfect to be amazing.",
            "Do something today that your future self will thank you for.",
            "Work hard in silence, let your success be the noise.",
            "A little progress each day adds up to big results.",
            "Dream it. Wish it. Do it.",
            "Great things never come from comfort zones.",
            "Make yourself a priority.",
            "Don’t stop until you’re proud.",
            "The key to success is to start before you are ready.",
            "Stay focused and never give up.",
            "Your only limit is you.",
            "Doubt kills more dreams than failure ever will.",
            "Discipline is the bridge between goals and accomplishment.",
            "Success starts with self-belief.",
            "Focus on progress, not perfection.",
            "Never give up on a dream just because of the time it will take to accomplish it.",
            "Small steps every day.",
            "You are capable of amazing things.",
            "Work until your idols become your rivals.",
            "Don’t be afraid to start over.",
            "Take the risk or lose the chance.",
            "Act as if what you do makes a difference. It does.",
            "Everything you need is already inside you.",
            "Let your dreams be bigger than your fears.",
            "Courage doesn’t mean you don’t get afraid.",
            "Keep going. Everything you need will come to you.",
            "Live more, worry less.",
            "Make today count.",
            "Start small, think big.",
            "Progress, not perfection.",
            "Success is a journey, not a destination."
                        ]
        return random.choice(local_quotes)
