import random

def get_would_you_rather():
    would_you_rather_questions = [
        "Makan pizza setiap hari atau tidak pernah makan pizza lagi?",
        "Pergi ke masa depan atau kembali ke masa lalu?",
        "Bisa terbang atau bisa tidak terlihat?"
        "Apakah kamu lebih suka memiliki kekuatan terbang atau invisibilitas?",
        "Apakah kamu lebih suka hidup di dunia nyata atau dalam mimpi?",
        "Pilih mana: bisa terbang atau bisa tidak terlihat?",
        "Pilih mana: hidup di masa lalu atau masa depan?",
        "Pilih mana: selalu panas atau selalu dingin?",
        "Pilih mana: tidak pernah bisa berbohong atau selalu harus berkata jujur secara spontan?",
        "Pilih mana: kaya tapi kesepian, atau miskin tapi bahagia?",
        "Pilih mana: hidup tanpa internet atau tanpa makanan favorit selamanya?",
        "Pilih mana: punya waktu tak terbatas atau uang tak terbatas?",
        "Pilih mana: selalu lupa nama orang atau selalu lupa wajah mereka?",
        "Pilih mana: jadi superhero atau jadi miliarder?",
        "Pilih mana: membaca pikiran orang atau bisa teleportasi?",
        "Pilih mana: tidak pernah sakit lagi atau bisa hidup 200 tahun?",
        "Pilih mana: kerja dari rumah selamanya atau pergi ke kantor tapi punya rekan kerja seru?",
        "Pilih mana: makan makanan pedas tiap hari atau tidak boleh makan asin?",
        "Pilih mana: tidur 3 jam tapi selalu segar atau tidur 10 jam tapi tetap lelah?",
        "Pilih mana: liburan ke pegunungan atau ke pantai?",
        "Pilih mana: jadi terkenal tapi dibenci, atau tidak dikenal tapi dicintai?",
        "Pilih mana: tidak pernah bisa nonton film atau tidak pernah bisa dengar musik?",
        "Pilih mana: punya hewan peliharaan naga atau unicorn?",
        "Pilih mana: harus menyanyi setiap bicara atau menari setiap berjalan?",
        "Pilih mana: semua baju yang kamu punya sama atau tidak bisa pakai baju yang sama dua kali?",
        "Pilih mana: tidak pernah bisa tertawa atau tidak bisa menangis?",
        "Pilih mana: selalu lupa ulang tahun teman atau lupa ulang tahun sendiri?",
        "Pilih mana: jadi anak kecil selamanya atau langsung tua?",
        "Pilih mana: punya gigi seperti hiu atau telinga seperti kelinci?",
        "Pilih mana: harus makan es tiap hari atau minum sup panas setiap waktu?",
        "Pilih mana: naik roller coaster setiap pagi atau nonton film horor tiap malam?",
        "Pilih mana: bisa bicara semua bahasa atau bisa bermain semua alat musik?",
        "Pilih mana: punya teman banyak tapi palsu, atau satu teman sejati?",
        "Pilih mana: hidup di dunia game atau dunia film?",
        "Pilih mana: selalu lapar atau selalu mengantuk?",
        "Pilih mana: belajar dari buku atau dari pengalaman?",
        "Pilih mana: tubuh kuat tapi mudah sakit, atau tubuh lemah tapi jarang sakit?",
        "Pilih mana: tidak bisa merasakan rasa atau tidak bisa mencium bau?",
        "Pilih mana: selalu jujur atau selalu sopan?",
        "Pilih mana: wajah tua dengan tubuh muda atau wajah muda dengan tubuh tua?",
        "Pilih mana: punya kekuatan super hanya saat sedih atau hanya saat marah?",
        "Pilih mana: hidup 1 hari sebagai hewan favoritmu atau 1 bulan sebagai orang kaya?",
        "Pilih mana: tidak pernah tidur atau tidak pernah lapar?",
        "Pilih mana: selalu kedinginan atau selalu kepanasan?",
        "Pilih mana: punya robot pelayan atau mobil terbang?",
        "Pilih mana: bisa hidup di bawah laut atau di luar angkasa?",
        "Pilih mana: harus jalan mundur selamanya atau bicara terbalik?",
        "Pilih mana: jadi orang paling pintar di dunia atau paling lucu?",
        "Pilih mana: tidak bisa melihat warna atau tidak bisa mendengar musik?",
        "Pilih mana: punya rumah besar tapi di tempat sepi atau rumah kecil di tengah kota?",
        "Pilih mana: bertemu alien atau hantu?",
        "Pilih mana: selalu bangun kesiangan atau tidur terlalu cepat?",
        "Pilih mana: jadi pemimpin dunia atau penemu terbesar?",
        "Pilih mana: bekerja keras 5 tahun lalu pensiun atau kerja santai seumur hidup?",
        "Pilih mana: tidak bisa pakai internet atau tidak bisa nonton TV selamanya?",
        "Pilih mana: tidak punya HP atau tidak punya komputer?",
        "Pilih mana: bisa berbicara dengan hewan atau mengerti bahasa bayi?",
        "Pilih mana: selalu kehabisan baterai atau sinyal lemah terus?",
        "Pilih mana: hanya bisa makan satu makanan selamanya atau tidak boleh makan makanan yang sama dua kali?",
        "Pilih mana: punya waktu 25 jam sehari atau libur 4 hari seminggu?",
        "Pilih mana: jadi karakter anime favoritmu atau karakter game favoritmu?",
        "Pilih mana: bisa menghentikan waktu atau bisa mempercepat waktu?",
        "Pilih mana: jalan kaki kemana-mana atau naik sepeda ke mana-mana?",
        "Pilih mana: jadi guru atau murid selamanya?",
        "Pilih mana: rambut berubah warna setiap hari atau suara berubah setiap bicara?",
        "Pilih mana: tertawa setiap mendengar nama atau menangis saat mendengar musik?",
        "Pilih mana: tidak pernah bisa mandi atau tidak pernah bisa menyikat gigi?",
        "Pilih mana: bisa melukis dengan indah atau menyanyi dengan indah?",
        "Pilih mana: hidup tanpa lampu atau tanpa kipas?",
        "Pilih mana: punya banyak uang tapi tidak bisa menikah atau cinta sejati tapi miskin?",
        "Pilih mana: bisa hidup di film favoritmu atau buku favoritmu?",
        "Pilih mana: kedinginan tanpa jaket atau kehujanan tanpa payung?",
        "Pilih mana: tidak punya tangan atau tidak punya kaki?",
        "Pilih mana: jadi terkenal di media sosial atau terkenal di dunia nyata?",
        "Pilih mana: bisa teleportasi ke masa depan atau ke masa lalu?",
        "Pilih mana: ulang tahun tiap bulan atau libur nasional tiap minggu?",
        "Pilih mana: gigi berwarna-warni atau rambut bersinar dalam gelap?",
        "Pilih mana: tidak pernah nonton YouTube atau TikTok lagi?",
        "Pilih mana: tidur di kasur es atau kasur api (tidak sakit)?",
        "Pilih mana: punya suara seperti robot atau seperti chipmunk?",
        "Pilih mana: tidak pernah bosan atau tidak pernah lapar?",
        "Pilih mana: jadi penulis terkenal atau aktor terkenal?",
        "Pilih mana: punya kekuatan api atau es?",
        "Pilih mana: tidak bisa berbicara atau tidak bisa mendengar?",
        "Pilih mana: tinggal di kapal laut atau di rumah pohon?",
        "Pilih mana: lupa cara membaca atau cara menulis?",
        "Pilih mana: bisa menyelam seperti ikan atau terbang seperti burung?",
        "Pilih mana: punya 3 mata atau 4 tangan?",
        "Pilih mana: jadi alien atau robot?",
        "Pilih mana: hidup di dunia sihir atau teknologi super canggih?",
        "Pilih mana: jadi detektif atau ilmuwan?",
        "Pilih mana: tidak bisa berhenti bersin atau cegukan selamanya?",
        "Pilih mana: semua makanan terasa manis atau semua terasa asin?",
        "Pilih mana: bisa membekukan waktu atau menggandakan diri?",
        "Pilih mana: tidur di siang hari saja atau hanya di malam hari?",
        "Pilih mana: hidup tanpa teman atau tanpa keluarga?",
        "Pilih mana: jadi sangat tinggi atau sangat kecil?",
        "Pilih mana: tidak bisa merasa sedih atau tidak bisa merasa senang?",
        "Pilih mana: selalu cepat tua atau tidak pernah dewasa?",
        "Pilih mana: jadi karakter kartun atau tokoh sejarah?",
        "Pilih mana: melihat masa depan orang lain atau masa depanmu sendiri?",
        "Pilih mana: jadi penguasa laut atau raja langit?",
        "Pilih mana: hanya bisa berlari atau hanya bisa merangkak?",
        "Pilih mana: tidak pernah punya mimpi atau selalu mimpi buruk?",
        "Pilih mana: hidup di kota besar atau kota kecil?",
        "Pilih mana: jadi penjahit atau penari?",
    ]
    return random.choice(would_you_rather_questions)
